version: '2'
services:
  app:
    build: .
    depends_on:
      - db
    links:
      - "db"
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    environment:
      - MYSQL_URL=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
        - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password 
volumes:
  mysql-data: